---
- name: Playbook that Creates hosts in Satellite using the Ansible Foreman Modules
  hosts: localhost
  vars:
    sat_username: "admin"
    sat_password: "redhat"
    sat_url: "https://satellite6.testlab.org"
    host_fqdn: 

  tasks:
  - name: Create a host in Satellite6
    redhat.satellite.host:
      username: "{{ sat_username }}"
      password: "{{ sat_password }}"
      server_url: "{{ sat_url }}"
      name: "{{ host_fqdn }}"
      hostgroup: "RHEL7_Dev"
      organization: "RedHat"
      location: "RDU"
      state: present
      validate_certs: no
      build: true

  - name: Power on the built host
    redhat.satellite.host_power:
      username: "{{ sat_username }}"
      password: "{{ sat_password }}"
      server_url: "{{ sat_url }}"
      hostname: "{{ host_fqdn }}"
      state: on
      validate_certs: no