---
- name: Playbook that Creates hosts in Satellite using the Ansible Foreman Modules
  hosts: localhost
  tasks:
  - name: Create a host in Satellite6
    theforeman.foreman.foreman_host:
      username: "admin"
      password: "redhat"
      server_url: "https://satellite6.testlab.org"
      name: "testy.testlab.org"
      hostgroup: "RHEL7_Dev"
      organization: "RedHat"
      location: "RDU"
      state: present
      validate_certs: no
      build: true

  - name: Power on the built host
    theforeman.foreman.foreman_host_power:
      username: "admin"
      password: "redhat"
      server_url: "https://satellite6.testlab.org"
      hostname: "testy.testlab.org"
      state: on
      validate_certs: no